### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by Landovil** [vlnahp/Btcbf#11]
Hi
The program does not output well. How to fix it? I do not see any generated wallets.

**Comment by Landovil** [comment]
![Uploading IMG_20211211_173952.jpg…]()

**Comment by Landovil** [comment]
![IMG_20211211_175122](https://user-images.githubusercontent.com/95962082/145679064-c05be57f-2acb-44ec-bef1-8a77f1bcd04b.jpg)

**Comment by vlnahp** [comment]
Hi Landovil!
In brute force mode, the wallets are not printed. Printing all the wallets will significantly slow down the program. To print a wallet use `[gen]`. 
You also gave me the idea to add batch wallet generation option. Thank you!

**Comment by Landovil** [comment]
@vlnahp . Yes, thank
I understand correctly he takes from all possible keys? R = 10000000000 ....... 10e15 I have 6 - i7 9750 their capacity is 1 = 18.000 it = 6 * 18.000 = 108.000it It is possible to divide the range of all keys into 6 machines. What would they not generate randomly? Or just random

**Comment by vlnahp** [comment]
> You need to add a verification system to the program. Feeling that the function of comparison-output to the file and r = 1000000 ........ At 10e15 are not correct.

I'm developing a new speed and progress measurement snippet. This would be solved in the next update. 

> I do not understand why in the code you take a private key and assign it to a variable and compare this variable with address.txt, the address contains only addresses but not private keys.

Only the public address is compared with the addresses in the address.txt. If we had the private key of the rich bitcoin wallets there was no need to brute them!!🙃
