### ISSUE TITLE
How can I see if Btcbf is really working?

### ISSUE THREAD

**Issue by vlnahp** [vlnahp/Btcbf#13]
Hey! How this supouse to work?What should i see if its realy working?

_Originally posted by @Werevalis in https://github.com/vlnahp/Btcbf/issues/12#issuecomment-998022532_

**Comment by vlnahp** [comment]
Hi @Werevalis!
To see the addresses you need to remove the comments from part of the code below:
```python
        #else: # uncommenting this part makes our code slow down
            #print ('false')
            #print(wif.decode("utf-8"))
            #print(z)
```
It has to look like this:
```python 
        else: # uncommenting this part makes our code slow down
            print ('false')
            print(wif.decode("utf-8"))
            print(z)
```
But it is recommended to keep it commented. Printing all the addresses makes us very slow!

**Comment by Werevalis** [comment]
What do you want to do? <<options: [gen]: generate wallet address and private key, [brute1]: brute force bitcoin offline, [brute2]: brute force bitcoin online, [exit]: exit>> brute1
How many cores to be used? (leave empty to use all available cores):
Starting ...
  0%|                                                                                        | 0/1e+16 [00:00<?, ?it/s]Exception in thread Thread-1:
Running ...
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "multiprocessing\pool.py", line 519, in _handle_workers
  File "multiprocessing\pool.py", line 499, in _wait_for_updates
  File "multiprocessing\connection.py", line 884, in wait
  File "multiprocessing\connection.py", line 816, in _exhaustive_wait
ValueError: need at most 63 handles, got a sequence of length 130
  0%|                                                              | 1571753/1e+16 [00:52<92251961:45:51, 30110.77it/s]

**Comment by Werevalis** [comment]
I have this errors and should the 0% change?

**Comment by vlnahp** [comment]
You have too many cores and it seems that the program can't handle all of them. I don't know any fix to it. Just reduce the number of cores used by the program.
