### ISSUE TITLE
Ram issue

### ISSUE THREAD

**Issue by meesvw** [vlnahp/Btcbf#17]
I have been testing the script and discovered an issue with the RAM usage going up. If you run the script long enough the ram usage will slowly go up.

Tested the script inside a limited container. Not sure how much it goes up in what span of time.

**Comment by vlnahp** [comment]
Hi!
I've not noticed it yet. Right now I'm at the university, and I don't have access to my personal computer. So I'll check it later.
I also noticed your fork. It seems to have nice improvements. I'll check that too!

**Comment by meesvw** [comment]
It's a good and simple Python program :) I have removed the tqdm in my version which seems to have solved the issue ? However my version right now doesn't allow for custom cpu usage, visual it/s and generating a wallet. Which I will add, but I split the bruteforce function in to two different onces:

- Traditional bruteforce (TBF)
- Random bruteforce (RBF)

TBF will generate every BTC wallet it can and split the load over multiple cores.

RBF will like it says just randomly generate wallets.

I also discovered that using the `in` instead of `find` to be faster in my runs of 10000 roughly 1 - 2 secs.

**Comment by vlnahp** [comment]
> It's a good and simple Python program

Yes, I started learning python by developing it.

>  I have removed the tqdm in my version which seems to have solved the issue

Most probably that's right. I have implemented a new progress management system that will be available in the next update. It also reduces the impact on the speed of the main process.

> Which I will add, but I split the bruteforce function in to two different onces

I'm going to add sequential/random option too!

> I also discovered that using the in instead of find to be faster

I'll consider it in the next update!🤝
