### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by Uroniq-git** [vlnahp/Btcbf#20]
Error:
Expecting value: line 1 column 1 (char 0)
  File "C:\Users\ffeam\Desktop\Btcbf-main\Btcbf.py", line 110, in multiprocessing
    tuple(results)
  File "C:\Users\ffeam\Desktop\Btcbf-main\Btcbf.py", line 113, in <module>
    multiprocessing()
![image](https://user-images.githubusercontent.com/97581520/149199126-a00b5b0a-9258-4e06-a473-03f8bed51182.png)

**Comment by meesvw** [comment]
Do you get the same error when you use `brute1` ?

**Comment by Fapsap** [comment]
> Do you get the same error when you use `brute1` ?

Yep

**Comment by meesvw** [comment]
This is what I could find:
https://itsmycode.com/jsondecodeerror-expecting-value-line-1-column-1-char-0/

Looks like a file is empty, or not found.

**Comment by Fapsap** [comment]
> This is what I could find:
> https://itsmycode.com/jsondecodeerror-expecting-value-line-1-column-1-char-0/
> 
> Looks like a file is empty, or not found.

Ok, thx :)

**Comment by vlnahp** [comment]
The response from the api is empty. Most probably the limit has been reached. You can use a paid api or wait till tomorrow to use the free api. Or you can use the offline(brute1) mode.

**Comment by meesvw** [comment]
> The response from the api is empty. Most probably the limit has been reached. You can use a paid api or wait till tomorrow to use the free api. Or you can use the offline(brute1) mode.

Probably should add a try function and quit program if this happens.

**Comment by vlnahp** [comment]
> > The response from the api is empty. Most probably the limit has been reached. You can use a paid api or wait till tomorrow to use the free api. Or you can use the offline(brute1) mode.
> 
> Probably should add a try function and quit program if this happens.

Will be added to the next update! 🤝
