### ISSUE TITLE
Any success stories from anyone here? 

### ISSUE THREAD

**Issue by LU5GOON** [vlnahp/Btcbf#28]
No issue to report as all is running smooth

Just wanted to see if people have had some good results here?

Curious is all!

**Comment by labrechejeremy** [comment]
Hi everyone
just start look in this and i got error can someone help me , Thanks
python /home/kali/Btcbf/Btcbf.py
Traceback (most recent call last):
  File "/home/kali/Btcbf/Btcbf.py", line 3, in <module>
    from bit import Key
ModuleNotFoundError: No module named 'bit'

**Comment by 3subs** [comment]
> Hi everyone just start look in this and i got error can someone help me , Thanks python /home/kali/Btcbf/Btcbf.py Traceback (most recent call last): File "/home/kali/Btcbf/Btcbf.py", line 3, in from bit import Key ModuleNotFoundError: No module named 'bit'

just run pip3 install bit

**Comment by 3subs** [comment]
> No issue to report as all is running smooth
> 
> Just wanted to see if people have had some good results here?
> 
> Curious is all!

as far as i know the only people lucky enough to get private keys with balance from random generations were 4 dudes back in 2015-2016 because of the btc puzzles
other than that i dont think anyone will ever get a private key but it is nice to pretend
fun fact: the possibility of getting a private key is so low that a 64 bit pc will not even notice that it is not 0

**Comment by vlnahp** [comment]
> No issue to report as all is running smooth
> 
> Just wanted to see if people have had some good results here?
> 
> Curious is all!

Honestly using python and random brute, the probability to find a valid key is very small.
My main goal for this project was to start learning Python and programming in general.
Using the 32BTC puzzle your chance will increase. If you are curious to do it with Btcbf wait until the next commit. I'll implement it soon.

**Comment by LU5GOON** [comment]
> > No issue to report as all is running smooth
> > Just wanted to see if people have had some good results here?
> > Curious is all!
> 
> Honestly using python and random brute, the probability to find a valid key is very small. My main goal for this project was to start learning Python and programming in general. Using the 32BTC puzzle your chance will increase. If you are curious to do it with Btcbf wait until the next commit. I'll implement it soon.

I am 1,000% interested thank you for the information, you have done a great job.
Really keen on the 32BTC Puzzle. Cant wait for your release of that
