### ISSUE TITLE
Noob Issue 

### ISSUE THREAD

**Issue by labrechejeremy** [vlnahp/Btcbf#30]
Hi everyone im looking into this to learn and fun 
and try to start the .py file and when i start it show this

python3 /home/kali/Btcbf/Btcbf.py 
Traceback (most recent call last):
  File "/home/kali/Btcbf/Btcbf.py", line 3, in <module>
    from bit import Key
ModuleNotFoundError: No module named 'bit'

**Comment by 3subs** [comment]
> Hi everyone im looking into this to learn and fun and try to start the .py file and when i start it show this
> 
> python3 /home/kali/Btcbf/Btcbf.py Traceback (most recent call last): File "/home/kali/Btcbf/Btcbf.py", line 3, in from bit import Key ModuleNotFoundError: No module named 'bit'

pip3 install bit
or
pip install bit
or
python3 -m pip install bit
or
python -m pip install bit

**Comment by vlnahp** [comment]
Hey @labrechejeremy! is your problem solved?
