### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nawneet77** [vlnahp/Btcbf#35]
**from bit import Key
ModuleNotFoundError: No module named 'bit'**

**Comment by agakakskajesh** [comment]
http://gozombie.ru

**Comment by SubGlitch1** [comment]
> **from bit import Key ModuleNotFoundError: No module named 'bit'**

pip3 install bit

**Comment by nawneet77** [comment]
Bit is already installed

**Comment by SubGlitch1** [comment]
if you are running
`python3 btcbf.py`
then run python3 -m pip install bit

if you are running
`python btcbf.py`
then run python -m pip install bit

**Comment by vlnahp** [comment]
Hi everyone! 
It's been a while since I last checked my github profile!
@nawneet77 please provide full traceback message, python version, and your operating system.

**Comment by br0tx** [comment]
![image](https://user-images.githubusercontent.com/103357134/165909195-bbcc65fb-0453-4b7f-b06f-84249191d813.jpeg)![image](https://user-images.githubusercontent.com/103357134/165909196-72c7ddc6-f628-4ba3-a30e-8916523e1466.jpeg)

**Comment by vlnahp** [comment]
You have trouble compiling coincurve library. See guides [here](https://ofek.dev/coincurve/install).
Install the requirements based on your distribution. Then: `python3 -m pip install bit`

**Comment by br0tx** [comment]
Thnks, --upgrade pip, then install bit :)
