### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VuzzyM** [vlnahp/Btcbf#4]
Hello

I need to run btcbf.py in background mode on debian linux, how can i do that?  Run the program in the background, for example on a vps server

**Comment by VuzzyM** [comment]
> Hi!
> 
> You have to remove inputs first(see below). Then simply run the Btcbf.py in this format: `$ python Btcbf.py &`. You can see it is running in background by executing `$ jobs`. Wait! one more step: `$ disown %<job id>` (job id is [n] in the `$ jobs` return) makes the process keep running even if you close the terminal.
> 
> Modify the Btcbf.py multiprocessing function like below
> 
> ```python
> def multiprocessing():
>     if __name__ == "__main__":
>         with Pool(processes=num_of_cores()) as pool:
>             r = range(100000000000000000)
>             results = pool.imap_unordered(check_list, r)
>             tuple(results)
> ```

 def multiprocessing():

    if __name__ == "__main__":

        inp = input("What do you want to do? <<options: [gen]: generate wallet address and private key, [brute]: brute force bitcoin, [exit]: exit>> ")

        if inp == "gen":

            generate()

            print("Your wallet is ready!")

            print("exitting...")

            sleep(3)

 

> Hi!
> 
> You have to remove inputs first(see below). Then simply run the Btcbf.py in this format: `$ python Btcbf.py &`. You can see it is running in background by executing `$ jobs`. Wait! one more step: `$ disown %<job id>` (job id is [n] in the `$ jobs` return) makes the process keep running even if you close the terminal.
> 
> Modify the Btcbf.py multiprocessing function like below
> 
> ```python
> def multiprocessing():
>     if __name__ == "__main__":
>         with Pool(processes=num_of_cores()) as pool:
>             r = range(100000000000000000)
>             results = pool.imap_unordered(check_list, r)
>             tuple(results)
> ```


Remove this?
def multiprocessing():
    if __name__ == "__main__":
        inp = input("What do you want to do? <<options: [gen]: generate wallet address and private key, [brute]: brute force bitcoin, [exit]: exit>> ")
        if inp == "gen":
            generate()
            print("Your wallet is ready!")
            print("exitting...")
            sleep(3)
            exit()

Replace ?

def multiprocessing():
    if __name__ == "__main__":
        with Pool(processes=num_of_cores()) as pool:
            r = range(100000000000000000)
            results = pool.imap_unordered(check_list, r)
            tuple(results)
            exit()

**Comment by vlnahp** [comment]
Yes, because in background mode inputs don't work.

**Comment by vlnahp** [comment]
Let me know if it works. I will close this issue in 2 days.

**Comment by VuzzyM** [comment]
> Let me know if it works. I will close this issue in 2 days.

![1](https://user-images.githubusercontent.com/66425682/133503733-f4ecdddc-ae6b-45a7-a0e6-7cedb1849bfe.png)

Error, all packages installed

**Comment by vlnahp** [comment]
Oh yes. I forgot to remove "num_of_cores()".
```python
def multiprocessing():
    if __name__ == "__main__":
        with Pool(processes=<put the number of cores to be used here>) as pool:
            r = range(100000000000000000)
            results = pool.imap_unordered(check_list, r)
            tuple(results)
```
Example:  
```python
def multiprocessing():
    if __name__ == "__main__":
        with Pool(processes=1) as pool:
            r = range(100000000000000000)
            results = pool.imap_unordered(check_list, r)
            tuple(results)
```

**Comment by VuzzyM** [comment]
> Oh yes. I forgot to remove "num_of_cores()".
> 
> ```python
> def multiprocessing():
>     if __name__ == "__main__":
>         with Pool(processes=<put the number of cores to be used here>) as pool:
>             r = range(100000000000000000)
>             results = pool.imap_unordered(check_list, r)
>             tuple(results)
> ```
> 
> Example:
> 
> ```python
> def multiprocessing():
>     if __name__ == "__main__":
>         with Pool(processes=1) as pool:
>             r = range(100000000000000000)
>             results = pool.imap_unordered(check_list, r)
>             tuple(results)
> ```

Working

**Comment by vlnahp** [comment]
Fine! :ok_hand:
