### ISSUE TITLE
Hi!
What this "62"?

### ISSUE THREAD

**Issue by br0tx** [vlnahp/Btcbf#41]
![IMG_20220430_123319.jpg](https://user-images.githubusercontent.com/103357134/166100264-3223e68a-d357-4faa-810e-a564abc4d5c6.jpg)

Offline bf random

**Comment by vlnahp** [comment]
It's because the text has not been completely overwritten. 
Learn more about carriage return [here](https://www.pythonpool.com/carriage-return-python/).

**Comment by br0tx** [comment]
Thnks
