### ISSUE TITLE
About Uncompress and p2sh address

### ISSUE THREAD

**Issue by ghost** [vlnahp/Btcbf#45]
I have test result just out compress address, how can i modify code to uncompress, p2sh or both?
Many thanks.

**Comment by vlnahp** [comment]
> I have test result just out compress address, how can i modify code to uncompress, p2sh or both? Many thanks.

Sorry, I don't understand what you mean!

**Comment by ken2709** [comment]
My mean, Btcbf tool just scan P2PKH Compress address not scan for P2PKH Uncompressed, P2SH and Bech32 address ? Because i tested just found P2PKH Compress address. How can i scan P2PKH Uncompressed,..
Thanks.

**Comment by anshukrsingh** [comment]
is it possible to scan bech32 address too?
