### ISSUE TITLE
Address.txt file question.

### ISSUE THREAD

**Issue by marssystems** [vlnahp/Btcbf#50]
The address.txt file contains 3 types of bitcoin address - 1xxx, 3xxx and bc1. 
Does the program generate and check all 3 types of address or just the basic 1xxx ?

**Comment by vlnahp** [comment]
The program only generates P2PKH addresses. `address.txt` is a sample database and should be replaced with a rich one.

**Comment by marssystems** [comment]
I thought as much. Edited out the non 1xxx addresses and I will see how it goes.
