### ISSUE TITLE
Test of sequential mode fails.

### ISSUE THREAD

**Issue by marssystems** [vlnahp/Btcbf#51]
I created an address.txt file with the first 10 compressed bitcoin addresses from here - 

https://privatekeys.pw/keys/bitcoin/1

1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH
1cMh228HTCiwS8ZsaakH8A8wze1JR5ZsP
1CUNEBjYrCn2y1SdiUMohaKUi4wpP326Lb
1JtK9CQw1syfWj1WtFMWomrYdV3W2tWBF9
17Vu7st1U1KwymUKU4jJheHHGRVNqrcfLD
1Cf2hs39Woi61YNkYGUAcohL2K2q4pawBq
19ZewH8Kk1PDbSNdJ97FP4EiCjTRaZMZQA
1EhqbyUMvvs7BfL8goY6qcPbD6YKfPqb7e
1HSxWThjiwbC4dJbXHMpBfwRenB12UguG5
13DaZ9nfmJLfzU6oBnD2sdCiDmf3M5fmLx

to test the program in sequential mode.

I ran the program with range = 1-100 and 1 core.

The program didn't find any of the addresses in the file - why is that?

**Comment by vlnahp** [comment]
I tested it and it is working. You may re-install the `bit` library since it's the core of the program.

**Comment by marssystems** [comment]
Yes - sorry - I had some random white space in my address.txt file which caused the program to fail - all fixed now and works as it should.
