### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by burgerpants42** [vlnahp/Btcbf#58]
Just curious, how many addresses are generated and checked per second? I'm using the windows release on 6 cores and it's just zipping by. Using my own address.txt I put together too. Love how it's not lagging up my whole computer like other similar programs. :)

**Comment by vlnahp** [comment]
The rate is shown in its/second. I used tqdm in that version.

**Comment by vlnahp** [comment]
Yes, the windows version is old.
