### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by cc2627** [vlnahp/Btcbf#59]
Is there a process for use

**Comment by marssystems** [comment]
Usage

Just execute this command: $ python Btcbf.py or $ python3 Btcbf.py on Linux, Btcbf tells you what to do!

Type your desired action and follow instructions. (I love to interact with my program🙂)

Results will be saved to foundkey.txt in the main directory.

**Comment by OmartGhani** [comment]
How use is this can I use this from termux android?

**Comment by marssystems** [comment]
No

**Comment by OmartGhani** [comment]
Why no

**Comment by OmartGhani** [comment]
Any alternatif mode for I can use from droid termux? Like this scripts mode

**Comment by marssystems** [comment]
Only for Linux, Windows and Mac - read the instructions !!

**Comment by OmartGhani** [comment]
Ok thx you no any information, in front thx you for your answers

**Comment by marssystems** [comment]
If you install python3 on your android device - you can try running the program.

**Comment by vlnahp** [comment]
I have not tested it on Android.
Most probably you will run into library issues...

**Comment by OmartGhani** [comment]
> I have not tested it on Android. Most probably you will run into library issues...

Btw how I can the open file on my termux file Btcbf after I downloaded?

**Comment by OmartGhani** [comment]
Cause I already downloaded the file
( blockchair_bitcoin_addresses_and_balance_October_05_2023.tsv.gz ) on my android trx you

**Comment by OmartGhani** [comment]
I can do it but error after run the
 $ pip install -r requirements.txt on termux but it's fun to learn it, :)

**Comment by OmartGhani** [comment]
![Screenshot_20231007-003058](https://github.com/vlnahp/Btcbf/assets/147170735/e5b81d81-9476-4814-92fb-b6d402b72734)

**Comment by marssystems** [comment]
Looking good !! - Keep going and let us know if you succeed in getting it running.

**Comment by OmartGhani** [comment]
Ok dude I'm waiting to fix it the file so I can run on my termux, hehe

**Comment by OmartGhani** [comment]
Folder is empty so I cannot run $ pip install - r requirements.txt  and run $ python Btcbf.py after I follow the Quick start his fix that MIN

![Screenshot_20231015-021934](https://github.com/vlnahp/Btcbf/assets/147170735/979e4229-83ae-41da-a7b9-349ab11650eb)
