### ISSUE TITLE
Crashes during online and offline brute force operation

### ISSUE THREAD

**Issue by T30001** [vlnahp/Btcbf#61]
Hi, 

When I run the Python3 Btcbf.py command and follow all instructions, the program starts running but after a while it exits Terminal and reboots the system with no error message at all. What could be the issue? This happens with both offline and online brute force operation - I have my own address.txt file. 

Thanks!

**Comment by SubGlitch1** [comment]
Could you monitor your system's resource usage during this? It is extremely uncommon for a python script to cause a system crash like that. How big is your address.txt?

**Comment by T30001** [comment]
> Could you monitor your system's resource usage during this? It is extremely uncommon for a python script to cause a system crash like that. How big is your address.txt?

It's 1.8GB
<img width="946" alt="Screenshot 2023-01-18 at 00 19 07" src="https://user-images.githubusercontent.com/122944790/213044138-40f08280-bceb-46a5-bb28-6167ff0ac341.png">

**Comment by vlnahp** [comment]
Check `/var/syslog`. You can find the cause of the reboot there.
