### ISSUE TITLE
Btcbf.py won't run

### ISSUE THREAD

**Issue by LU5GOON** [vlnahp/Btcbf#71]
Hello,

I used to have this running whilst on an older build of Windows. I am currently on Windows 11 23H2 and having some issues here.

All requirements installed successfully, i am also running Python 3.12

![image](https://github.com/vlnahp/Btcbf/assets/100285625/805e46d0-2c5b-4076-b605-7afaaa5863f0)

Any ideas on what the issue here could be?

Thank you.

**Comment by LU5GOON** [comment]
Just adding more to this, with some research it appears there is a known issue with cffi-1.16.0 with how pip fails to build wheels with it when installed. 

If there is a known workaround here for now, happ to use that if someone can please share.

Thank you.

**Comment by vlnahp** [comment]
Hello @LU5GOON 
The easy solution?! Linux OS.

In case of insisting on keeping using windows, you need to install `Microsoft C++ Build Tools`
