### ISSUE TITLE
how do i know if i find any 

### ISSUE THREAD

**Issue by Praveenbabu9392** [vlnahp/Btcbf#74]

**Comment by marssystems** [comment]
found privatekey and address saved to "foundkey.txt

**Comment by Praveenbabu9392** [comment]
![Screenshot 2024-06-30 060330](https://github.com/vlnahp/Btcbf/assets/138370428/40766b3c-1c98-4f2a-9846-f059a27faba0)

this is the process right

**Comment by marssystems** [comment]
Yes
