### ISSUE TITLE
segwit & legacy keys

### ISSUE THREAD

**Issue by PopeDollar** [vlnahp/Btcbf#9]
Hi! Is it possible to add algo for segwit & legacy address? Because I see that the script only works for addresses that begin with 1..., not for 3... and bc1.... thank you!

**Comment by vlnahp** [comment]
Hi! It is possible for sure. But based on the addresses database, the most dominant algo is the best choice.

**Comment by PopeDollar** [comment]
I understand, cool! If I find anything, I'll let you know.
